services:
  nginx:
    image: nginx:1.29
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/html/:/usr/share/nginx/html:ro
    environment:
      DOMAIN: localhost